(function(){
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const root=document.getElementById('extended-player');
  const exercise=window.__EXERCISE__||{};
  const preview=!!window.__PREVIEW__;
  const lang=(exercise.opzioni&&exercise.opzioni.linguaComandi)||'it';
  const strings={
    it:{verify:'Verifica',next:'Continua',prev:'Indietro',reset:'Azzera',correct:'Risposta corretta!',wrong:'Risposta errata!',complete:'Esercizio completato',step:'Step'},
    en:{verify:'Check',next:'Continue',prev:'Back',reset:'Reset',correct:'Correct answer!',wrong:'Wrong answer!',complete:'Exercise completed',step:'Step'},
    fr:{verify:'Vérifier',next:'Continuer',prev:'Retour',reset:'Réinitialiser',correct:'Bonne réponse !',wrong:'Réponse incorrecte !',complete:'Exercice terminé',step:'Étape'},
    es:{verify:'Verificar',next:'Continuar',prev:'Atrás',reset:'Reiniciar',correct:'¡Respuesta correcta!',wrong:'Respuesta incorrecta',complete:'Ejercicio completado',step:'Paso'},
    de:{verify:'Prüfen',next:'Weiter',prev:'Zurück',reset:'Zurücksetzen',correct:'Richtige Antwort!',wrong:'Falsche Antwort!',complete:'Übung abgeschlossen',step:'Schritt'}
  };
  const t=strings[lang]||strings.it;
  let current=0, state={steps:{},currentStep:0};
  let api=null, initialized=false, saveTimer=null;
  function findAPI(win){let tries=0;while(win&&tries<20){if(win.API)return win.API;tries++;if(win.parent&&win.parent!==win)win=win.parent;else break;}try{return window.opener?findAPI(window.opener):null}catch(e){return null}}
  function scormInit(){if(preview)return;api=findAPI(window);if(!api)return;try{var r=api.LMSInitialize('');initialized=(r==='true'||r===true)}catch(e){}try{const raw=api.LMSGetValue('cmi.suspend_data');if(raw){const s=JSON.parse(raw);if(s&&s.extendedState)state=s.extendedState;current=Number(state.currentStep||0)}}catch(e){}}
  function calcScore(){const steps=exercise.steps||[];let done=0,correct=0;steps.forEach((st,i)=>{const s=state.steps[i];if(s&&s.verified){done++;if(s.correct)correct++;}});return {done,correct,total:steps.length,score:steps.length?Math.round(correct*100/steps.length):0}}
  function persist(){state.currentStep=current;if(preview)return;clearTimeout(saveTimer);saveTimer=setTimeout(()=>{if(!api)return;try{const q=calcScore(),threshold=Number((exercise.metadata||{}).passThreshold||60);const status=q.done===q.total?(q.score>=threshold?'passed':'failed'):'incomplete';api.LMSSetValue('cmi.core.lesson_location',String(current));api.LMSSetValue('cmi.suspend_data',JSON.stringify({v:2,extendedState:state,score:q.score,status}));api.LMSSetValue('cmi.core.score.raw',String(q.score));api.LMSSetValue('cmi.core.lesson_status',status);api.LMSSetValue('cmi.core.exit','suspend');api.LMSCommit('')}catch(e){}},650)}
  function finish(){if(!api||!initialized)return;try{api.LMSSetValue('cmi.core.exit','suspend');api.LMSCommit('');setTimeout(()=>{try{api.LMSFinish('')}catch(e){}},750)}catch(e){}}
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function assetSrc(obj){return obj&&obj.previewSrc?obj.previewSrc:(obj&&obj.src?obj.src:'')}
  function mediaHtml(item, compact=false){if(!item)return '';if(item.type==='image')return `<img src="${esc(assetSrc(item))}" alt="${esc(item.alt||item.label||'')}"/>`;if(item.type==='audio')return `<span class="xp-audio"><button type="button" data-audio-src="${esc(assetSrc(item))}" aria-label="play">▶</button><span>${esc(item.label||'Audio')}</span></span>`;return `<span>${esc(item.text||item.label||'')}</span>`}
  function wireAudio(){$$('[data-audio-src]').forEach(btn=>{btn.onclick=e=>{e.stopPropagation();const a=new Audio(btn.dataset.audioSrc);a.play().catch(()=>{})}})}
  function ensureStep(i){return state.steps[i]||(state.steps[i]={})}
  function render(){const steps=exercise.steps||[];if(!steps.length){root.innerHTML='<div class="xp-shell"><div class="xp-body"><div class="xp-card">Nessuno step.</div></div></div>';return}current=Math.max(0,Math.min(current,steps.length-1));const step=steps[current], ss=ensureStep(current);root.innerHTML=`<div class="xp-shell"><div class="xp-header"><div class="xp-title">${esc(exercise.titolo||'Esercizio')}</div><div class="xp-stepno">${t.step} ${current+1} / ${steps.length}</div></div><div class="xp-body"><div class="xp-card"><div class="xp-instruction">${step.consegna||''}</div>${step.suggerimento?`<div class="xp-hint">${step.suggerimento}</div>`:''}<div id="xp-content"></div><div id="xp-feedback" class="xp-feedback"></div></div></div><div class="xp-footer"><div class="xp-actions"><button class="xp-btn secondary" id="xp-prev" ${current===0?'disabled':''}>${t.prev}</button>${exercise.opzioni&&exercise.opzioni.mostraReset?`<button class="xp-btn secondary" id="xp-reset">${t.reset}</button>`:''}</div><div class="xp-actions"><button class="xp-btn primary" id="xp-verify">${t.verify}</button><button class="xp-btn primary" id="xp-next" ${current===steps.length-1?'disabled':''}>${t.next}</button></div></div></div>`;
    renderStep(step,ss);
    $('#xp-prev').onclick=()=>{current--;persist();render()};
    $('#xp-next').onclick=()=>{current++;persist();render()};
    $('#xp-verify').onclick=()=>verify(step,ss);
    const reset=$('#xp-reset');if(reset)reset.onclick=()=>{state.steps[current]={};persist();render()};
    wireAudio();
  }
  function renderStep(step,ss){const host=$('#xp-content');switch(step.builderMode){case 'mediaTiles':renderMediaTiles(step,ss,host);break;case 'mediaChoice':renderMediaChoice(step,ss,host);break;case 'match':renderMatch(step,ss,host);break;default:renderTextTiles(step,ss,host)}}
  function renderTextTiles(step,ss,host){const tiles=(step.builderTiles||[]);const assigned=ss.assigned||{};const parsed=step.builderSegments||[];host.innerHTML=`<div class="xp-text">${parsed.map(seg=>seg.type==='text'?seg.html:`<span class="xp-slot ${assigned[seg.id]?'filled':''}" data-slot="${esc(seg.id)}">${assigned[seg.id]?esc(assigned[seg.id]):'&nbsp;'}</span>`).join('')}</div><div class="xp-tiles">${tiles.map((v,i)=>`<button class="xp-tile" data-tile-index="${i}">${esc(v)}</button>`).join('')}</div>`;let selected=null;$$('[data-tile-index]',host).forEach(btn=>btn.onclick=()=>{selected=Number(btn.dataset.tileIndex);$$('.xp-tile',host).forEach(x=>x.classList.remove('selected'));btn.classList.add('selected')});$$('[data-slot]',host).forEach(slot=>slot.onclick=()=>{if(selected===null)return;const val=tiles[selected];assigned[slot.dataset.slot]=val;ss.assigned=assigned;ss.verified=false;persist();render()})}
  function renderMediaTiles(step,ss,host){const tiles=step.mediaTiles||[], assigned=ss.assigned||{};host.innerHTML=`<div class="xp-text">${(step.mediaSegments||[]).map(seg=>seg.type==='text'?seg.html:`<span class="xp-slot ${assigned[seg.id]?'filled':''}" data-slot="${esc(seg.id)}">${assigned[seg.id]?mediaHtml(tiles.find(x=>x.id===assigned[seg.id]),true):'&nbsp;'}</span>`).join('')}</div><div class="xp-tiles">${tiles.map((it,i)=>`<button class="xp-tile" data-media-id="${esc(it.id)}">${mediaHtml(it)}</button>`).join('')}</div>`;let selected=null;$$('[data-media-id]',host).forEach(btn=>btn.onclick=e=>{if(e.target.closest('[data-audio-src]'))return;selected=btn.dataset.mediaId;$$('.xp-tile',host).forEach(x=>x.classList.remove('selected'));btn.classList.add('selected')});$$('[data-slot]',host).forEach(slot=>slot.onclick=()=>{if(!selected)return;assigned[slot.dataset.slot]=selected;ss.assigned=assigned;ss.verified=false;persist();render()});wireAudio()}
  function renderMediaChoice(step,ss,host){const m=step.mainMedia||null;const choices=step.choiceTiles||[];host.innerHTML=`${m?`<div class="xp-media-main">${m.type==='video'?`<video src="${esc(assetSrc(m))}" controls></video>`:`<audio src="${esc(assetSrc(m))}" controls></audio>`}</div>`:''}<div class="xp-choice-grid">${choices.map(it=>`<button class="xp-choice ${ss.selected===it.id?'selected':''}" data-choice="${esc(it.id)}">${mediaHtml(it)}</button>`).join('')}</div>`;$$('[data-choice]',host).forEach(btn=>btn.onclick=e=>{if(e.target.closest('[data-audio-src]'))return;ss.selected=btn.dataset.choice;ss.verified=false;persist();render()});wireAudio()}
  function renderMatch(step,ss,host){const pairs=step.matchPairs||[], right=(step.rightOrder||pairs.map(p=>p.right.id)).map(id=>pairs.map(p=>p.right).find(x=>x.id===id)).filter(Boolean);const matches=ss.matches||{};host.innerHTML=`<div class="xp-match-wrap"><svg class="xp-lines"></svg><div class="xp-col xp-left">${pairs.map(p=>`<button class="xp-match-item" data-left="${esc(p.left.id)}">${mediaHtml(p.left)}</button>`).join('')}</div><div class="xp-col xp-right">${right.map(it=>`<button class="xp-match-item" data-right="${esc(it.id)}">${mediaHtml(it)}</button>`).join('')}</div></div>`;let active=ss.activeLeft||null;function sync(){$$('[data-left]',host).forEach(b=>{b.classList.toggle('active',b.dataset.left===active);b.classList.toggle('matched',!!matches[b.dataset.left])});$$('[data-right]',host).forEach(b=>b.classList.toggle('matched',Object.values(matches).includes(b.dataset.right)));drawLines(host,matches)}$$('[data-left]',host).forEach(btn=>btn.onclick=e=>{if(e.target.closest('[data-audio-src]'))return;active=btn.dataset.left;ss.activeLeft=active;sync()});$$('[data-right]',host).forEach(btn=>btn.onclick=e=>{if(e.target.closest('[data-audio-src]')||!active)return;matches[active]=btn.dataset.right;ss.matches=matches;ss.verified=false;ss.activeLeft=null;active=null;persist();sync()});sync();wireAudio();window.addEventListener('resize',()=>drawLines(host,matches),{once:true})}
  function drawLines(host,matches){const svg=$('.xp-lines',host),wrap=$('.xp-match-wrap',host);if(!svg||!wrap)return;const wr=wrap.getBoundingClientRect();svg.setAttribute('width',wr.width);svg.setAttribute('height',wr.height);svg.innerHTML='';Object.entries(matches).forEach(([l,r])=>{const a=$(`[data-left="${CSS.escape(l)}"]`,host),b=$(`[data-right="${CSS.escape(r)}"]`,host);if(!a||!b)return;const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect(),x1=ar.right-wr.left,y1=ar.top+ar.height/2-wr.top,x2=br.left-wr.left,y2=br.top+br.height/2-wr.top;svg.innerHTML+=`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="#17a2b8" stroke-width="3"/>`})}
  function verify(step,ss){let ok=false;if(step.builderMode==='mediaTiles'){const expected={};(step.mediaSegments||[]).filter(x=>x.type==='slot').forEach(x=>expected[x.id]=x.answer);ok=Object.keys(expected).length>0&&Object.keys(expected).every(k=>ss.assigned&&ss.assigned[k]===expected[k])}else if(step.builderMode==='mediaChoice'){ok=!!ss.selected&&ss.selected===step.correctChoiceId}else if(step.builderMode==='match'){ok=(step.matchPairs||[]).length>0&&(step.matchPairs||[]).every(p=>ss.matches&&ss.matches[p.left.id]===p.right.id)}else{const expected={};(step.builderSegments||[]).filter(x=>x.type==='slot').forEach(x=>expected[x.id]=x.answer);ok=Object.keys(expected).length>0&&Object.keys(expected).every(k=>ss.assigned&&ss.assigned[k]===expected[k])}ss.verified=true;ss.correct=ok;persist();const fb=$('#xp-feedback');fb.textContent=ok?t.correct:t.wrong;fb.className='xp-feedback '+(ok?'ok':'bad');if(step.builderMode==='match'){$$('.xp-match-item').forEach(el=>el.classList.add(ok?'correct':'wrong'))}else if(step.builderMode==='mediaChoice'){$$('.xp-choice').forEach(el=>{if(el.dataset.choice===ss.selected)el.classList.add(ok?'correct':'wrong')})}else{$$('.xp-slot').forEach(el=>el.classList.add(ok?'correct':'wrong'))}}
  scormInit();render();window.addEventListener('beforeunload',finish);
})();
